### ISSUE TITLE
In ODM2 database schema, "ODM2_for_MySQL.sql" for mysql 

### ISSUE THREAD

**Issue by cdesyoun** [ODM2/ODM2#100]
Would you please fix these problems below?
  -- please add "AUTO_INCREMENT" constraint in the table, "externalidentifiersystems" and "spatialoffsets"
  -- please replace "BIT" type with "TINYINT (1)" type as the bool type.
  -- please fix the spelling error, "CitationExternalIdentifier" and "CitationExternalIdentifierURI" columns in the table "CitationExternalIdentifiers".

**Comment by horsburgh** [comment]
I've done the following:

* Added AUTO_INCREMENT constraint to externalidentifiesystems and spatial offsets entities in the DBWrench file
* Fixed spelling errors in CitationExternalIdentifiers entities in the DBWrench file

TODO (will get to this shortly):
[ ] Change the BIT data type in the Python mapping file for the script that generates the DDL SQL Script for MySQL
[ ] Rerun the Python script to regenerate the DDL SQL scripts
[ ] Update documentation

**Comment by horsburgh** [comment]
These have all been implemented.
