### ISSUE TITLE
CV_ResultTypeCV typo

### ISSUE THREAD

**Issue by sreeder** [ODM2/ODM2#102]
There is a table in the database named: CV_ResultTypeCV. It should be: CV_ResultType

**Comment by emiliom** [comment]
The version of the blank database DDL I last used (for PostgreSQL), from abt. May 10, doesn't have CV_ResultTypeCV; it has the correct, expected name, CV_ResultType. *However*, it does have a similar problem/error, but on a different table: `CV_DatasetTypeCV` should be `CV_DatasetType`.

What I've described is also what's [present in the current DbWrench schema diagram](http://odm2.github.io/ODM2/schemas/ODM2_Current/schemas/ODM2CV.html).

**Comment by horsburgh** [comment]
I just fixed this in the DBWrench schema and the DDL SQL scripts.
