### ISSUE TITLE
Add Unique Constraints

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2#104]
We just discussed this here at USU.  We want to add a Unique constraint on the the TimeSeriesResultValues table so that the database throws an error if a user tries to insert duplicate values.  This is needed for the Streaming Data Loader application.  We should probably do this for all of the ResultValue tables in the Results schema.  We should also add Unique constraints to the following:

* Codes (e.g., OrganizationCode, SamplingFeatureCode, MethodCode, VariableCode, etc.)
* CV Terms (the names will already be unique because they are in a primary key)

If there are no objections, I will add these constraints in DBWrench and update the DDL SQL Scripts.

**Comment by emiliom** [comment]
Looks good, and it's a change that shouldn't impact anything else in the software ecosystem.

**Comment by horsburgh** [comment]
I added these unique constraints to the DBWrench schema a long time ago.  But, the Python script that creates the DDL SQL scripts wasn't picking them up.  @Castronova modified the Python script to handle the unique constraints, so I just updated the DDL SQL scripts now.  Closing.
