### ISSUE TITLE
Update CV Loader Script

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2#105]
Need to update CV Loader script to handle the consolidation of SpecimenMediumCV, ReferenceMaterialCV, and SampledMediumCV into a single CV called Medium.

Also, need to update once the UnitsTypeCV has been added to the CV System

* [x] Medium CV Updates
* [x] UnitsTypeCV Updates

**Comment by sreeder** [comment]
This has been applied in commit 61d9b9f62804e6f125fe682078a45db8652e4a1f

**Comment by horsburgh** [comment]
Done.  Closing.
