### ISSUE TITLE
CVUnitsType description length

### ISSUE THREAD

**Issue by sreeder** [ODM2/ODM2#106]
When trying to insert the UnitsType CV from the webservice into the database there is a 'data truncated' error. This is occurring because the length of the description field in the database is not sufficient for the data coming from the webservice.

**Comment by horsburgh** [comment]
@sreeder - I updated the DBWrench schema and the DDL SQL Scripts for generating the database to fix this issue.  I increased the length of the Definition field from 1000 characters to 5000 characters.  Hopefully that is long enough.  When you test and it works, please close this issue.

**Comment by sreeder** [comment]
Works great.
