### ISSUE TITLE
CVUnitsType in cvload.py

### ISSUE THREAD

**Issue by miguelcleon** [ODM2/ODM2#107]
the CVUnitsType fails to load from cvload.py, I think the definitions field defined in  http://vocabulary.odm2.org/ must be longer then 1000 characters as I get the error "Load was unsuccessful: (psycopg2.DataError) value too long for type character varying(1000)" 

I changed my table with:
 ALTER TABLE odm2.cv_unitstype ADD COLUMN definition character varying(1500); 
Then I ran cvload.py again and it succesfully loaded the cv_unitstype table. 

This also happens for cv_variablename and maybe others.

**Comment by horsburgh** [comment]
@miguelcleon - I just fixed this in the schema files and the DDL SQL scripts yesterday. Stephanie tested it with the cv loader script and it worked so we closed the original issue.  I'm going to close this one because I think it's fixed, but let us know if you are still having issues.

**Comment by miguelcleon** [comment]
ok, I see that the definition field length is changed to 5000, that should do it.
