### ISSUE TITLE
Issues with ReferenceMaterialValues in generate schema scripts

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODM2#113]
In using the generate schema scripts for MSSQL, there are issues with the ReferenceMaterialValues table:
- CitationID is non-nullable (it should be nullable)
- ReferenceMaterialID is set as the primary key, but not as an identity

**Comment by horsburgh** [comment]
I just changed this in the DBWrench schema.  I will update the DDL SQL scripts shortly in response to another issue.  Closing.
