### ISSUE TITLE
make the length of some fields longer? 

### ISSUE THREAD

**Issue by miguelcleon** [ODM2/ODM2#121]
It would be nice of some of the varchar fields were longer 

ODM2.Methods.methoddescription change from 500 to 5,000?
ODM2.Actions.actiondescription change from 500 to 5,000?
ODM2.ExtensionProperties.propertydescription  change from 500 to 5,000?

Maybe any field with description in the name. right now, I'm linking to files with full method descriptions. It would be nice to have the complete method in the database.

**Comment by emiliom** [comment]
I've checked the 3 suggested field length increases suggested by @miguelcleon against the ODM2 2.0.0 release (via the [schema browser](http://odm2.github.io/ODM2/schemas/ODM2_Current/tables/ODM2ExtensionProperties_ExtensionProperties.html)), and they are there.

I would close this issue, except for the additional, broader suggestion:
> Maybe any field with description in the name. right now, I'm linking to files with full method descriptions. It would be nice to have the complete method in the database.

@horsburgh, do you remember if other `description` fields were also increased?

**Comment by miguelcleon** [comment]
Yes, I changed them here, I think that was all the changes that were needed for this, but not entirely certain [https://github.com/ODM2/ODM2/commit/cad9f6f536756b0bf550df6676314a796f59cb19]

**Comment by emiliom** [comment]
Thanks, @miguelcleon. But FYI, as you probably know by now (but maybe not in late June when you submitted that commit), those individual DDL files are not managed manually. Instead, they're generated via a script from the master DbWrench schema file. So, unless @horsburgh et al incorporated your changes in the DbWrench schema directly, they would have been overwritten.

**Comment by horsburgh** [comment]
@emiliom and @miguelcleon - I made these changes a while ago and so the 2.0.0 release should have a length of 5000 for all description fields. All the ones I just checked had been changed, so I'm going to close this. If you notice any I missed, let me know in a new issue.

**Comment by emiliom** [comment]
Great, thanks for checking. FYI, I just happened to see these open issues from a while ago, so was double-checking before they got closed (rather than us continuing to ignore them :wink:)
