### ISSUE TITLE
Unique Constraint contains more than 16 columns in sql server script

### ISSUE THREAD

**Issue by daniellu** [ODM2/ODM2#122]
Hi,

I have tried to run the sql server schema script to generate an empty schema. But the script fails due to some tables have unique constraint that contains more than 16 columns, which is not allowed by sql server.

Has the script been tested? If yes, what version of the sql server was used?

Regards,
Daniel

**Comment by horsburgh** [comment]
I just fixed this and made a push.  We have not had this issue for both MySQL and SQL Server.  So, the fix I pushed was to leave the first 16 columns in the table in the unique constraint.  This constraint is designed to keep users from entering duplicate records into the table. So, the constraint limited to the first 16 columns won't be perfect, but should still serve the purpose. 
 
I just tested on SQL Server 2012, but is should also work on other versions. Closing.
