### ISSUE TITLE
Misspelling of Involved

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/ODM2#124]
Hi,

I'd like to let you know that there is a misspelling of the word involved in the core_actions.md. It is located on the last paragraph of *In Situ* Observation Example. "See the documentation for RelatedActions for more **invovled** examples of Actions with in situ measurements." 

Thanks.

**Comment by emiliom** [comment]
Thanks, Don. I've fixed it. I'm sure it won't be the last mispelling we have :wink:
