### ISSUE TITLE
Misspellings in core_relatedactions.md

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/ODM2#125]
Hi,

There are various misspellings within core_relatedactions.md.

1. `their`: "Create a series of **Actions** that are recorded separately, each with `thier` own granular Method description."

2. `hierarchy` and `hierarchies`: paragraph right above simple sensor example "However, as in the previous example, each of the Results can be traced all the way back to the site visit during which the samples were collected by tracing up the `heirarchy` using each Action's immediate parent." and within complex sensor example "Representing the sequence of Actions related to a sensor deployment and Result involves potentially multiple separate `heirarchies` of Actions, all of which must be related to the initial sensor deployment (because the sensor deployment is the Action to which the Result should be linked)."

3. `technician` & `retrieves`: paragraph right above complex sensor example "During that same site visit, the `technican` then `retrives` the sensor and datalogger, ending data collection."

4. `activities`: last sentence of the document "Actions that have been related (e.g., sensor cleaning and calibration `activites` or any other `activies` for which a formal relationship has been created)."

Thanks.

**Comment by horsburgh** [comment]
Just fixed all of these.  Thanks!

**Comment by emiliom** [comment]
Thanks, Jeff. FYI, @lsetiawan works with me, and is starting to wrap his brain around ODM2. That's how he noticed the misspellings in the documentation.
