### ISSUE TITLE
Truncated identifier

### ISSUE THREAD

**Issue by sluedtke** [ODM2/ODM2#126]
Hi there, 

hope that is not duplicated but I could not find anything in the open or closed issues. 

I imported the sql file to create the schema within a postgreSQL data base (9.5 on Kubuntu 16.04) and got two notifications:

`psql:ODM2_for_PostgreSQL.sql:1177: NOTICE:  identifier "fk_pointcoverageresultvalueannotations_pointcoverageresultvalues" will be truncated to "fk_pointcoverageresultvalueannotations_pointcoverageresultvalue" `

and 

`psql:ODM2_for_PostgreSQL.sql:1653: NOTICE:  identifier "fk_spatialreferenceexternalidentifiers_externalidentifiersystems" will be truncated to "fk_spatialreferenceexternalidentifiers_externalidentifiersystem"`

It seems like identifier names can not be longer than 63 characters. 

So is that a problem??

Cheers, 

Stefan

**Comment by horsburgh** [comment]
@sluedtke - the naming requirements are all a little different across the RDBMS. This warning shouldn't affect your implementation. If the truncation had resulted in you having multiple foreign key relationships with the same name, I think it would have thrown an error and not a notice.

If you try it and it works OK, let us know so we can close this issue. If you do have problems, we'll use this issue to work it out.

**Comment by sluedtke** [comment]
it were only two notifications as stated above. No errors, no warnings. I just wanted to be sure, that' s why I was  asking. Thanks for your fast reply. 

I ' ll close this issue.

**Comment by emiliom** [comment]
I use ODM2 on postgresql and have seen those warnings. They are in fact
harmless.

Just adding to what's already been concluded.
