### ISSUE TITLE
Time for first ODM2 release?

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2#127]
It seems that ODM2 has been stable for the last several months. @horsburgh and @AmberSJones, is it time for our first release, even if it is labeled as an alpha or beta release?

**Comment by emiliom** [comment]
YES, or at least the first **tagged** release, regardless of what version number it's given. Otherwise it's getting hard to track things like the recent issue submissions about mispellings in field names and such.

**Comment by aufdenkampe** [comment]
Release 2.0.0 is out! https://github.com/ODM2/ODM2/releases/tag/v2.0.0
