### ISSUE TITLE
Are units of measure a controlled vocabulary, or not?

### ISSUE THREAD

**Issue by dr-shorthair** [ODM2/ODM2#131]
Documentation is contradictory: 
- https://github.com/ODM2/ODM2/blob/master/doc/ODM2Docs/core_units.md says "Units are a controlled vocabulary in ODM2"
- http://vocabulary.odm2.org/units/ says "Units are not treated as a CV in ODM2"

**Comment by horsburgh** [comment]
@dr-shorthair - thank you for pointing this out. I just modified the documentation to make the two consistent. Our current position is that Units is not a CV in ODM2. There's way too much going on our there with Units for us to say which system is definitive.

But, we added the Units list to the CV pages so people could adopt that list if they wanted to (i.e., if they needed something convenient). OK - I realize that the distinction here is a little fuzzy. We put a huge amount of work in trying to figure out Units and we wanted people to be able to capitalize on that and have the list that out colleagues at Stroud worked out, but also leave it open for others to adopt whatever system (or systems) they want to.

I'm going to close this for now, but please let us know if we need to continue discussion.
