### ISSUE TITLE
Issue with MSSQL ODM2 database when querying various endpoints 

### ISSUE THREAD

**Issue by Elijahwalkerwest** [ODM2/ODM2#143]
When querying various tables with an MSSQL database, returning this error: 

TypeError at /v1/samplingfeatures/
'NoneType' object is not iterable

Request Method: GET
Request URL: http://127.0.0.1:8000/v1/samplingfeatures/
Django Version: 1.11.6
Python Executable: C:\ProgramData\Anaconda2\envs\odm2restenv\python.exe
Python Version: 2.7.14
Python Path: ['C:\\Users\\Elijah\\Desktop\\Projects\\odm2restapi', 'C:\\Users\\Elijah\\Desktop\\Projects\\odm2restapi', 'C:\\Users\\Elijah\\Desktop\\Projects\\odm2restapi\\odm2rest\\settings', 'C:\\Users\\Elijah\\Desktop\\Projects\\odm2restapi\\odm2rest', 'C:\\Users\\Elijah\\Desktop\\Projects\\odm2restapi\\odm2proj\\odm2proj', 'C:\\Users\\Elijah\\Desktop\\Projects\\odm2restapi\\odm2proj', 'C:\\Users\\Elijah\\Desktop\\Projects\\odm2restapi\\odm2proj\\odm2rest', 'C:\\Users\\Elijah\\Desktop\\Projects\\odm2restapi\\api', 'C:\\ProgramData\\Anaconda2\\envs\\odm2restenv\\python27.zip', 'C:\\ProgramData\\Anaconda2\\envs\\odm2restenv\\DLLs', 'C:\\ProgramData\\Anaconda2\\envs\\odm2restenv\\lib', 'C:\\ProgramData\\Anaconda2\\envs\\odm2restenv\\lib\\plat-win', 'C:\\ProgramData\\Anaconda2\\envs\\odm2restenv\\lib\\lib-tk', 'C:\\ProgramData\\Anaconda2\\envs\\odm2restenv', 'C:\\ProgramData\\Anaconda2\\envs\\odm2restenv\\lib\\site-packages', 'c:\\users\\elijah\\desktop\\projects\\odm2pythonapi']
Server time: Mon, 23 Oct 2017 23:14:04 +0000
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'api']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:  

File "C:\ProgramData\Anaconda2\envs\odm2restenv\lib\site-packages\django\core\handlers\exception.py" in inner
  41.             response = get_response(request)

File "C:\ProgramData\Anaconda2\envs\odm2restenv\lib\site-packages\django\core\handlers\base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "C:\ProgramData\Anaconda2\envs\odm2restenv\lib\site-packages\django\core\handlers\base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "C:\ProgramData\Anaconda2\envs\odm2restenv\lib\site-packages\django\views\decorators\csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)

File "C:\ProgramData\Anaconda2\envs\odm2restenv\lib\site-packages\django\views\generic\base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "C:\ProgramData\Anaconda2\envs\odm2restenv\lib\site-packages\rest_framework\views.py" in dispatch
  489.             response = self.handle_exception(exc)

File "C:\ProgramData\Anaconda2\envs\odm2restenv\lib\site-packages\rest_framework\views.py" in handle_exception
  449.             self.raise_uncaught_exception(exc)

File "C:\ProgramData\Anaconda2\envs\odm2restenv\lib\site-packages\rest_framework\views.py" in dispatch
  486.             response = handler(request, *args, **kwargs)

File "C:\Users\Elijah\Desktop\Projects\odm2restapi\api\views.py" in get
  151.         sfs = get_samplingfeatures(**get_kwargs)

File "C:\Users\Elijah\Desktop\Projects\odm2restapi\api\core.py" in get_samplingfeatures
  183.     for sf in sampling_features:

Exception Type: TypeError at /v1/samplingfeatures/
Exception Value: 'NoneType' object is not iterable
Request information:
USER: AnonymousUser

GET: No GET data

POST: No POST data

FILES: No FILES data

When querying all samplingfeatures, or filtering by ID, type, or any other parameter

**Comment by emiliom** [comment]
@Elijahwalkerwest, this is actually an ODM2 REST API issue, so it belongs [there](https://github.com/ODM2/ODM2RESTfulWebServices), not in this repo. I've copied your posting there at https://github.com/ODM2/ODM2RESTfulWebServices/issues/18, and will follow up there.

I'm closing this issue here.

**Comment by lsetiawan** [comment]
Let me elaborate a bit about this Issue. It may seem like this is an error on ODM2RestAPI, but it's actually an error that occurs when querying using ODM2PythonAPI against MSSQL. I am not sure what's going on, I do not have a way to test with MSSQL.

With Postgresql and Mysql the function to query samplingfeatures works just fine. Thanks.

**Comment by emiliom** [comment]
Thanks, @lsetiawan. Still, that's not an issue that belongs in the ODM2 repo. As I mentioned over on the new issue I opened on the ODM2 REST API repo, it belongs in the ODM2PythonAPI repo.

**Comment by lsetiawan** [comment]
I was too quick to reopen. I moved it to PythonAPI Issue.
