### ISSUE TITLE
Need to update SSL certificate on the ODM2.org site

### ISSUE THREAD

**Issue by PleiadesAustralia** [ODM2/ODM2#168]
Hi Admin,

We have corporate and government clients using ODM2 as an interoperability standard, but their firewalls no longer allow them to access the site.

Can someone please attend to this housekeeping task?

Thanks,
Sam

**Comment by ptomasula** [comment]
Thanks Sam, I enabled HTTPS for the www.odm2.org site. Let us know if you are still not being routed through the secure protocol.

**Comment by PleiadesAustralia** [comment]
Works great

Sent from Android device

On 04-Aug-2023 21:34, Paul Tomasula ***@***.***> wrote:

Thanks Sam, I enabled HTTPS for the www.odm2.org<http://www.odm2.org> site. Let us know if you are still not being routed through the secure protocol.

**Comment by emiliom** [comment]
@PleiadesAustralia could you point us to examples of your use of ODM2, if the projects are accessible online? I and like others would be very interested in hearing about how you're using ODM2. Thanks!

**Comment by PleiadesAustralia** [comment]
Thanks Emilion,

I, and my company Pleiades, have been specialising in ODM2 with the following projects:

Western Australian Department of Water and Environmental Regulation 
- We have been working with the Department over the last 6 years to convert all of their siloed environmental datasets over to ODM2 as the Departmental standard.  These datasets include:
1. Statewide phytoplankton sampling including Field Collection and Lab Analysis.  The program integrates field observation, taxonomic identification (linked to other online taxonomy systems), biovolume estimation, water chemistry/physical properties, and ecological/health risk information.
2. Seagrass community investigations: These are multi-scale studies that tie together Estuarine scale meadow mapping and measurement, meadow community structure transects and quadrants of seagrass/associated epiphytes/fauna associations, individual specimen measurement, branch productivity growth, tissue sample chemistry, and in future real-time monitoring from photometers, etc...
3. Multi-theme ecological surveys of stream reaches including Fish, Macroinvertebrates, Vegetation, Aquatic Habitat Biomes, Stream Connectivity, Insitu Water Quality, Geomorphology and Flow channels/drops, Pollution Sources, Erosion characteristics, Land Use, and Logger Deployment and Management.
4. Estuarine water chemistry and physical measurements.
We have also implemented a generalised spreadsheet tool for cataloguing datasets according to different themes (Using the Citation table), and a method for embedding Ecological Metadata Language statements on Datasets through adding an additional DatasetXML field to Datasets.  We are in the process of making a generic interface for PowerBI to ODM2 to allow various kinds of standard data exploration and performance against targets for the Department.

On the other hand we have been experimenting with using ODM2 as a universal data interoperability standard for ESG reporting.  There is a global need that many parties have flagged for such an interoperability standard to be created and we find that ODM2 has been adaptable to almost any form of derived indicator and linkages to associated base data.  We have used ODM2 to model and generate:
- Greenhouse Gas and Energy Inventories for Landfills, Industrial Facilities, SMEs, and Government Departments.
- Pollutant inventories (PRTRs) for Landfills and Industrial Facilities
- Infrastructure Sustainability Design Ratings for a major freeway extension

During the past year, we have invested in developing a commercial SaaS platform for ESG Accounting and Reporting using an SQL Server database implementing ODM2 which we will be launching in November.  Our hope is to make ESG accounting that is transparent and exchangeable between organizations with a mutual interest in the data (such as different parties in an Infrastructure Development Alliance, or between value chain partners mutually reporting to the European Carbon Border Adjustment mechanism).

**Comment by PleiadesAustralia** [comment]
my website - www.pleiadesconsulting.com.au

Sent from Android device

On 17-Aug-2023 04:51, Emilio Mayorga ***@***.***> wrote:

@PleiadesAustralia<https://github.com/PleiadesAustralia> could you point us to examples of your use of ODM2, if the projects are accessible online? I and like others would be very interested in hearing about how you're using ODM2. Thanks!

**Comment by emiliom** [comment]
Thank you so much, @PleiadesAustralia ! That's fantastic. It's really great to hear about your extensive use of ODM2.
