### ISSUE TITLE
Develop guidelines and conventions for MMI-hosted vocabularies

### ISSUE THREAD

**Issue by emiliom** [ODM2/ODM2#62]
These guidelines and conventions should include:

1. **Common attributes** to be used in all (or nearly all) vocabularies. My tentative, first suggestion is: *term, name, definition, category, notes, provenance, and provenance_uri*. These will be reviewed and finalized soon.
2. **Case conventions for vocabulary attributes and terms**. Probably a choice between CamelCase and lowercase_underscore. Will consult MMI's John Graybeal and Carlos Rueda for suggestions.
3. **Descriptive vocabulary information/metadata**.  For example: keywords, creator, brief description, references

**Comment by horsburgh** [comment]
Closing this issue for now.  Not that we don't want to continue discussions with the MMI guys, but we have now implemented the ODM2 CV system and so I don't think we need this open issue anymore.

**Comment by emiliom** [comment]
Note that this issue also includes description of conventions for vocabularies that apply and are being used independently of MMI hosting. So we should refer back to comments on this issue (with updates as needed) when I/we get around to documenting these conventions in [an appropriate page in the wiki](https://github.com/ODM2/ODM2/blob/master/doc/ODM2Docs/concept_controlledvocabs.md).
