### ISSUE TITLE
API Check List

### ISSUE THREAD

**Issue by jmeline** [ODM2/ODM2#66]
API written in Python using SQLAlchemy Progress Chart
***
- [ ] Like ODM 1 Backwards Compatability
    - [ ] Monitoring Site Locations
        - [x] Sites
        - [ ] SpatialReferences
    - [ ] Observation Values
        - [ ] DataValues
    - [ ] Value Grouping
        - [ ] Groups
        - [ ] Group Descriptions
    - [ ] Organizations
    - [ ] Series Catalog
    - [ ] Data Qualifiers
        - [ ] QualityControlLevels
        - [ ] Qualifers
    - [ ] ProcessingLevels
    - [x] Units
    - [x] Variables
    - [ ] Data Collection Methods
        - [ ] LabMethods
        - [x] Methods
    - [ ] Results
    - [ ] Data Sources
        - [ ] ISOMetaData
        - [x] Sources

***

**Comment by horsburgh** [comment]
Closing this as it should now be in the ODM2 API repository.
