### ISSUE TITLE
ODM2CV: Remove Figure from Front Page

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2#86]
I know you guys don't like the wider styling, but when I make my window narrow the figure placeholder wraps to the next line.  I would rather just remove it and extend the text to the full width of the page.

**Comment by jcaraballo17** [comment]
Placeholder removed.

**Comment by denvaar** [comment]
This issue is being tracked in the new repository: https://github.com/ODM2/ODM2ControlledVocabularies/issues
