### ISSUE TITLE
ODM2CV: Fix the width of the pages with tables

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2#87]
When I make my browser window narrow, the table on the vocabulary view page spills over the width of the page. I suggest fixing the width of the page to contain the table regardless of how narrow the browser gets.  This also happens on my phone browser. Two options:

1. Fix the width of the page to contain the table
2. Dynamically scale the table when the page gets narrow

![screenshot](https://cloud.githubusercontent.com/assets/3485902/7159389/08478b44-e33f-11e4-949e-c3448e095684.png)

**Comment by denvaar** [comment]
This issue is being tracked in the new repository: https://github.com/ODM2/ODM2ControlledVocabularies/issues
