### ISSUE TITLE
ODM2CV: Admin should receive an email when new terms or edits are received

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2#89]
I just submitted a new term.  As the submitter, I should receive an email stating that my term submission has been received.  As the admin, I should receive an email stating that a new or edited term has been submitted.  When the decision about accepting or rejecting has been made, the submitter should be notified via email about the decision.

**Comment by denvaar** [comment]
This issue is being tracked in the new repository: https://github.com/ODM2/ODM2ControlledVocabularies/issues
