### ISSUE TITLE
ODM2CV: Once Logged in I can't get back to the Requests page

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2#90]
Once I am logged in, if I navigate to the main page to view any of the CVs (I navigate away from the Requests page) there is no way that I can find to get back to the requests page except to log out and then log back in.  It would be nice to have a link at the top between my name and the "Logout" link that goes to the Requests page.

Jeff Horsburgh | Requests | Logout

**Comment by jcaraballo17** [comment]
Added a link to the requests page.

**Comment by horsburgh** [comment]
I'm closing this issue in the ODM2 repository.  We have moved it to the ODM2ControlledVocabularies repository https://github.com/ODM2/ODM2ControlledVocabularies/issues/4.
