### ISSUE TITLE
ODM2CV:  Add DataQualityTypeCV and RelationshipTypeCV

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2#94]
There are two additional Cvs that are ready to be added to the CV system:

DataQualityTypeCV: https://docs.google.com/spreadsheets/d/1s0RErY_87wU8_KH-KMLL5uE5XAuXyu3mNnfy7s3EVG0/edit#gid=0
RelationshipTypeCV:  https://docs.google.com/spreadsheets/d/1Y-RnD4p1aGyVIZXjgJ7kE_uDjmT2Gyx8pIUCOf0hLHQ/edit#gid=0

Just load the stuff that is highlighted in green.  I've got one additional CV that I'm working on (UnitsTypeCV) that I'm hoping to have done by the end of this week (if not sooner).

**Comment by denvaar** [comment]
I've added these CV's on the sandbox server and they are ready to be tested.

**Comment by denvaar** [comment]
This issue is being tracked in the new repository: https://github.com/ODM2/ODM2ControlledVocabularies/issues/1

**Comment by horsburgh** [comment]
Let's keep issues open until they have been pushed to production.  These look good and are ready to go to production.

**Comment by horsburgh** [comment]
Whoops.  Wrong repository.  I'll get this right eventually.
