### ISSUE TITLE
cv_relationshiptype not loaded from cvload.py

### ISSUE THREAD

**Issue by miguelcleon** [ODM2/ODM2#99]
The controlled vocabulary cv_relationshiptype is not loaded from cvload.py 
This is the controlled vocabulary found here http://vocabulary.odm2.org/relationshiptype/

**Comment by emiliom** [comment]
@miguelcleon, coincidentally I ran into this problem just this morning too. I've looked at [cvload.py](https://github.com/ODM2/ODM2/blob/master/src/load_cvs/cvload.py) and found the problem. I'll try to fix it right now, over the next hour. I'll send you the file via email, and also submit a pull request here on github. @horsburgh, let me know if someone from your team (@sreeder?) is already working on this right now.

FYI, I'm aware you're using PostgreSQL, and so am I (vers. 9.3). I've been working through some data loading this week, mapping from another PostgreSQL database.

**Comment by emiliom** [comment]
I've fixed cvload.py, and tested it on a blank, newly created postgresql database. Seems to work. I've sent the script to @miguelcleon via email (cc'd @horsburgh), and will submit a pull request in a bit.

**Comment by miguelcleon** [comment]
Great, thanks, does cvload.py work with a PosgreSQL database now? I had to make a modified version because in order to get it to run before.

**Comment by emiliom** [comment]
Yeah. The version currently on github (last updated abt 21 days ago) does work on PostgreSQL; I tested it a couple of days ago. My updates are on top of that version, and like I said, I tested it on PostgreSQL just now.

**Comment by miguelcleon** [comment]
Ok, great. I'll give it a try.

**Comment by miguelcleon** [comment]
Yes, it worked! My cv_relationshiptype table is now populated. Thanks!

**Comment by miguelcleon** [comment]
Well I suppose this should only be closed once these changes are actually applied to this project. I think I jumped the gun.

**Comment by emiliom** [comment]
No worries, Miguel. I was going to reopen it.

@horsburgh, I took the liberty of pushing my update directly w/o a pull request. Sorry, I'm in a rush, don't remember if I can create a pull request from my local repo w/o creating a new branch, and both Miguel and I tested this independently.

**Comment by horsburgh** [comment]
Thanks for working this out guys.  It should be fine.

**Comment by emiliom** [comment]
Thanks, Jeff. 

FYI, to add more information about my setup: all my work is on Ubuntu Linux (14.04). That includes the PostgreSQL 9.3 server and running cvload.py (more FYI: Python 2.7 on an Anaconda environment). It'll be kind of neat if Miguel is using PostgreSQL on Windows or MacOS, to get verification that things are working as expected on all kinds of platforms.

**Comment by miguelcleon** [comment]
Yes, I'm using PostgreSQL 9.3 on Windows Server 2012.

**Comment by emiliom** [comment]
Great to hear. Thanks for reporting that.
